esphome:
  name: smartoutletv1
  name_add_mac_suffix: True
  comment: 基于ESP32的墙壁智能插座，磁保持继电器+计量+LD2412人体存在。支持OTA与本地网页控制。
  project:
    name: "HA-DIYer.SmarOutlet-V1"
    version: "1.1.3"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
api:
# ==========================================
# 1. MQTT 连接配置
# ==========================================
mqtt:
  broker: "192.168.6.88"  # <--- 替换为你 Mosquitto 所在的宿主机 IP
  port: 1883
  id: mqtt_client         # 给 MQTT 客户端起个ID，方便后面调用

# ==========================================
# 2. 蓝牙网关与抓包配置
# ==========================================
esp32_ble_tracker:
  scan_parameters:
    interval: 5000ms        # 降低扫描频率节省功耗
    window: 1100ms
    active: false           # 被动扫描更省电
  on_ble_advertise:
    - mac_address: "00:00:70:38:AB:CD"
      then:
        - lambda: |-
            auto datas = x.get_manufacturer_datas();
            if (datas.empty()) return;
            auto &data = datas[0];
            if (data.data.empty()) return;
            std::string hex_data = format_hex_pretty(data.data);
            hex_data.erase(std::remove(hex_data.begin(), hex_data.end(), ' '), hex_data.end());
            hex_data.erase(std::remove(hex_data.begin(), hex_data.end(), '.'), hex_data.end());
            id(mqtt_client).publish("home/ble/custom_fan/raw", hex_data);
            ESP_LOGD("ble_adv", "收到风扇数据: %s", hex_data.c_str());

bluetooth_proxy:
  active: true
web_server:
  port: 80
  version: 3

wifi:
  ap:
    ssid: "SmartOutlet(V1) Hotspot"
    password: "12345678"

captive_portal:

substitutions:
  led_pin: GPIO27
  button_pin: GPIO0
  relay_a_pin: GPIO26
  relay_b_pin: GPIO25
  ld2412_tx_pin: GPIO3  
  ld2412_rx_pin: GPIO1  
  bl0940_tx_pin: GPIO21
  bl0940_rx_pin: GPIO5

globals:
  - id: var_energy
    type: float
    restore_value: yes
    initial_value: "0"
  - id: current_presence_seconds
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: last_presence_seconds
    type: uint32_t
    restore_value: yes
    initial_value: '0'
  - id: current_absence_seconds
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: last_absence_seconds
    type: uint32_t
    restore_value: yes
    initial_value: '0'

uart:
  - id: uart_bl0940
    tx_pin: $bl0940_tx_pin
    rx_pin: $bl0940_rx_pin
    baud_rate: 4800
    stop_bits: 1
    
  - id: uart_ld2412
    tx_pin: $ld2412_tx_pin
    rx_pin: $ld2412_rx_pin
    baud_rate: 115200 
    parity: NONE
    stop_bits: 1

output:
  - platform: gpio
    pin:
      number: $relay_a_pin
      mode:
        output: true
        pulldown: true
    id: relay_a_pin_output
  - platform: gpio
    pin:
      number: $relay_b_pin
      mode:
        output: true
        pulldown: true
    id: relay_b_pin_output

switch:
  - platform: template
    name: "Switch"
    id: outlet_switch
    device_class: outlet
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - output.turn_off: relay_a_pin_output
      - output.turn_on: relay_b_pin_output
      - delay: 100ms
      - output.turn_off: relay_b_pin_output
    turn_off_action:
      - output.turn_off: relay_b_pin_output
      - output.turn_on: relay_a_pin_output
      - delay: 100ms
      - output.turn_off: relay_a_pin_output

  - platform: restart
    name: "Restart"
    id: outlet_reset

  - platform: ld2412
    engineering_mode:
      name: "LD2412 工程模式 Eng"
      id: ld2412_eng_mode
    bluetooth:
      name: "LD2412 蓝牙控制 BT"
      id: ld2412_bluetooth

binary_sensor:
  - platform: gpio
    pin:
      number: $button_pin
      inverted: true
      mode:
        input: true
        pullup: true
    name: "button"
    internal: True
    on_click:
    - min_length: 50ms
      max_length: 350ms
      then:
        - if:
            condition:
              switch.is_on: outlet_switch
            then:
              - switch.turn_off: outlet_switch
            else:
              - switch.turn_on: outlet_switch
    on_multi_click:
      - timing:
          - ON for at least 10s
        then:
          - logger.log:
              level: INFO
              format: "FACTORY RESET"
          - button.press: btn_factory_reset

  - platform: ld2412
    has_target:
      name: "LD2412 有人 Target"
      id: ld2412_target
      on_press:
        then:
          - lambda: |-
              id(last_absence_seconds) = id(current_absence_seconds);
      on_release:
        then:
          - lambda: |-
              id(last_presence_seconds) = id(current_presence_seconds);
    has_moving_target:
      name: "LD2412 微动 Moving"
      id: ld2412_moving
    has_still_target:
      name: "LD2412 静止 Still"
      id: ld2412_still

status_led:
  pin:
    number: $led_pin
    inverted: true

sensor:
  - platform: bl0940
    uart_id: uart_bl0940
    voltage:
      name: 'Voltage'
      accuracy_decimals: 0
    current:
      name: 'Current'
    power:
      name: 'Power'
      accuracy_decimals: 1
    energy:
      name: 'Energy'
      accuracy_decimals: 3
      id: bl0940_energy
    read_command: 0x58
    write_command: 0xA8
    legacy_mode: false
    resistor_one: 0.51
    resistor_two: 1950
    update_interval: 1s

  - platform: template
    name: "Total Daily Energy"
    id: bl0940_DailyEnergy
    device_class: energy
    accuracy_decimals: 3
    unit_of_measurement: 'kWh'
    update_interval: 1min
    lambda: |-
      if ((id(var_energy) > id(bl0940_energy).state) || (id(var_energy) == 0) || isnan(id(var_energy))) {
        id(var_energy) = id(bl0940_energy).state;
      }
      return id(bl0940_energy).state - id(var_energy);

  - platform: ld2412
    moving_distance:
      name: "LD2412 运动距离 MDist"
      id: ld2412_moving_dist
    still_distance:
      name: "LD2412 静止距离 SDist"
      id: ld2412_still_dist
    moving_energy:
      name: "LD2412 运动能量 MEnergy"
      id: ld2412_moving_energy
    still_energy:
      name: "LD2412 静止能量 SEnergy"
      id: ld2412_still_energy
    detection_distance:
      name: "LD2412 检测距离 Det"
      id: ld2412_det_dist
    light:
      name: "LD2412 光照度 Lux"
      id: ld2412_light

  - platform: template
    name: "当前有人时长 P_Curr"
    id: sensor_curr_presence
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(current_presence_seconds);
    update_interval: 1s

  - platform: template
    name: "上次有人时长 P_Last"
    id: sensor_last_presence
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(last_presence_seconds);
    update_interval: 5s

  - platform: template
    name: "当前无人时长 A_Curr"
    id: sensor_curr_absence
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(current_absence_seconds);
    update_interval: 1s

  - platform: template
    name: "上次无人时长 A_Last"
    id: sensor_last_absence
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(last_absence_seconds);
    update_interval: 5s

  - platform: wifi_signal
    name: "WiFi RSSI"
    id: sensor_wifi_rssi
    update_interval: 60s

ld2412:
  uart_id: uart_ld2412

number:
  - platform: bl0940
    current_calibration: { name: Current Calibration }
    voltage_calibration: { name: Voltage Calibration }
    power_calibration: { name: Power Calibration }
    energy_calibration: { name: Energy Calibration }

  - platform: ld2412
    timeout: 
      name: "LD2412 存在超时 Timeout"
      id: ld2412_timeout
    min_distance_gate: 
      name: "LD2412 最小距离门 MinGate"
      id: ld2412_min_gate
    max_distance_gate: 
      name: "LD2412 最大距离门 MaxGate"
      id: ld2412_max_gate
    light_threshold: 
      name: "LD2412 光照阈值 Thresh"
      id: ld2412_light_thresh

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: id(var_energy) = id(bl0940_energy).state;

button:
  - platform: bl0940
    name: Reset Calibration
  - platform: factory_reset
    name: Factory Reset
    internal: True
    id: btn_factory_reset
    
  - platform: ld2412
    factory_reset: 
      name: "LD2412 恢复出厂 Reset"
      id: ld2412_factory_reset
    restart: 
      name: "LD2412 重启雷达 Restart"
      id: ld2412_restart
    query_params: 
      name: "LD2412 查询参数 Query"
      id: ld2412_query

text_sensor:
  - platform: ld2412
    version: 
      name: "LD2412 固件版本 Ver"
      id: ld2412_version
    mac_address: 
      name: "LD2412 MAC地址 MAC"
      id: ld2412_mac
  - platform: version
    name: "ESPHome Version"

interval:
  - interval: 1s
    then:
      - if:
          condition:
            binary_sensor.is_on: ld2412_target
          then:
            - lambda: |-
                id(current_presence_seconds)++;
                id(current_absence_seconds) = 0;
          else:
            - lambda: |-
                id(current_absence_seconds)++;
                id(current_presence_seconds) = 0;

  - interval: 5min
    then:
      - if:
          condition:
            lambda: |-
              return isnan(id(ld2412_det_dist).state);
          then:
            - logger.log: "LD2412 Restart"
            - button.press: ld2412_restart
