esphome:
  name: esp32-test
  friendly_name: ESP32 Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: "你的WiFi"
  password: "你的密码"

output:
  - platform: gpio
    pin: GPIO2
    id: led

light:
  - platform: binary
    name: "测试LED"
    output: led
