esphome:
  name: ble-test
  friendly_name: BLE Test

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: "y"

logger:
  level: VERY_VERBOSE

api:

ota:
  - platform: esphome

wifi:
  ssid: "CC"
  password: "chen1122"

web_server:

captive_portal:

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID

esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 320ms
    window: 30ms

button:
  - platform: restart
    name: Restart
