esphome:
  name: ble-test
  friendly_name: BLE Test

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

logger:
  level: VERY_VERBOSE

api:

ota:
  - platform: esphome

wifi:
  ssid: "CC"
  password: "chen1122"

web_server:

captive_portal:

esp32_ble_tracker:

sensor:
  - platform: uptime
    name: Uptime

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP

button:
  - platform: restart
    name: Restart
