esphome:
  name: midea-send-only

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble:

esp32_ble_server:
  id: ble_server
  manufacturer_data: []

button:
  - platform: template
    name: "Midea Light Toggle"

    on_press:

      - lambda: |-
          std::vector<uint8_t> pkt1 = {
            0x19,0x1C,0x48,0x80,0x27,0x70,0x00,0x00,
            0x01,0x71,0x70,0x06,0x5F,0xC8,0x6F,0xB8,
            0x48,0x48,0xA7,0xF0,0x80,0x80,0x97,0x2F
          };

          id(ble_server).set_manufacturer_data(pkt1);

      - delay: 120ms

      - lambda: |-
          std::vector<uint8_t> pkt2 = {
            0x19,0x1A,0x48,0x80,0x27,0x70,0x00,0x00,
            0x01,0x26,0x27,0x70,0x70,0x00,0x5F,0xC8,
            0x6F,0xB8,0x48,0x48,0xA7,0xF0,0x80,0x82
          };

          id(ble_server).set_manufacturer_data(pkt2);

      - delay: 120ms

      - lambda: |-
          std::vector<uint8_t> empty = {};
          id(ble_server).set_manufacturer_data(empty);
