esphome:
  name: c6-eth-gateway
  friendly_name: "C6 Ethernet Gateway"

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  framework:
    type: esp-idf

# ✅ 尝试 W5500 配置
ethernet:
  type: DM9051
  clk_pin: GPIO10
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO13
  # interrupt_pin: GPIO4


api:
  encryption:
    key: "4jGVSQw9/v+e8QCB/CSQIwGFcWS3Opo4oHSRbkq41RI="

ota:
  - platform: esphome
    password: "chen1122"
  - platform: web_server

web_server:
  port: 80
  version: 2

logger:
  level: DEBUG  # 开启 DEBUG 方便看以太网日志

sensor:
  - platform: uptime
    name: "Uptime"
