esphome:
  name: esp32c6-eth

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LOG_DEFAULT_LEVEL_VERBOSE: "y"

logger:
  level: VERBOSE # 调低日志，减少spi刷屏干扰，需要再切VERY_VERBOSE

api:
  encryption:
    key: "4jGVSQw9/v+e8QCB/CSQIwGFcWS3Opo4oHSRbkq41RI="

ota:
  - platform: esphome
    password: "chen1122"

web_server:
  port: 80

ethernet:
  type: W5500
  # 原有引脚不变
  clk_pin: GPIO6
  mosi_pin: GPIO7
  miso_pin: GPIO2
  cs_pin: GPIO10
  interrupt_pin: GPIO4
  reset_pin: GPIO5
  # 关键修复：SPI时钟降到8MHz（C6高频极易超时，原厂推荐≤10M）
  spi_clk_speed: 8MHz
  # 开启硬件复位时序，上电自动复位W5500
  reset_duration: 10ms
