esphome:
  name: esp32c6-eth

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LOG_DEFAULT_LEVEL_VERBOSE: "y"

logger:
  level: VERBOSE

api:
  encryption:
    key: "4jGVSQw9/v+e8QCB/CSQIwGFcWS3Opo4oHSRbkq41RI="

ota:
  - platform: esphome
    password: "chen1122"

web_server:
  port: 80

# 单独定义SPI总线，在这里控制时钟速率8M
spi:
  id: w5500_spi
  clk_pin: GPIO6
  mosi_pin: GPIO7
  miso_pin: GPIO2
  clock_speed: 8MHz

ethernet:
  type: W5500
  spi_id: w5500_spi
  cs_pin: GPIO10
  # 替换strap引脚：原GPIO4(INT)→GPIO11；原GPIO5(RST)→GPIO12
  interrupt_pin: GPIO11
  reset_pin: GPIO12
