name: Build ESPHome

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ESPHome
        uses: esphome/build-action@v6
        with:
          yaml-file: midea-send-only.yaml

      - name: Copy firmware files
        run: |
          mkdir output
          cp ./.esphome/build/midea-send-only/.pioenvs/midea-send-only/*.bin output/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/*.bin
