name: Build & Release ESPHome

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.yaml"

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 检测变更 YAML
        id: changed
        run: |
          FILES=$(git diff --name-only HEAD^ HEAD \
            | grep '\.yaml$' \
            | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES" >> $GITHUB_OUTPUT

  build:
    needs: detect
    if: needs.detect.outputs.files != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yaml: ${{ fromJson(needs.detect.outputs.files) }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: esphome/build-action@v6
        with:
          yaml-file: ${{ matrix.yaml }}

      - name: 收集 BIN
        run: |
          mkdir -p output
          find .esphome/build -type f -name "*.bin" -exec cp -f {} output/ \;

      - name: 上传到 Release（永久保存）
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: output/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
